### ISSUE TITLE
Audio player

### ISSUE THREAD

**Issue by nikjdwhite** [wgcowan/KalturaVideo#2]
Hello again,

This plugin has been really helpful to us for embedding Kaltura video in Omeka!

We attempted putting in an oral history with audio only. In the item/show view there was no player display, and in exhibit/show view a player loaded, but then it would hang after pressing play (as below).
![Capture](https://user-images.githubusercontent.com/2364690/57036519-22c81c00-6c1a-11e9-9ab4-11886f1ee4ec.PNG)

We were wondering if the plugin as is works with audio-only Kaltura items, and if not, if you have plans to add audio support.  

Thank you!

**Comment by wgcowan** [comment]
The plugin should work fine with audio only files. I just tested it and it loaded a .wav file from Kaltura just fine. For audio files, you still need to have all the Kaltura Video fields filled in. The reason I mention this is because the end field below the video says 0:00:00 (Playback: 0.00.00 - 0.00.00) which indicates there is no value in that End field or an incorrect value. 

Will

**Comment by nikjdwhite** [comment]
Thanks for your quick response!

Oh, I see. I wanted to play the whole file, and I was thinking that would be the default behavior if a segment was not specified. It does not seem to work when in second format, but is working correctly when I put in a segment time in 00:00:00 format. Thank you so much!

**Comment by wgcowan** [comment]
Unfortunately, there is no easy way to get the length of the media file from the Kaltura api but the way the playback part of the API works you need a start and end point. 

Will
